### ISSUE TITLE
Add support for fields' Javadoc

### ISSUE THREAD

**Issue by joffrey-bion** [dnault/therapi-runtime-javadoc#11]
I just realized we couldn't access the Javadoc of a class's fields, or did I just miss it somewhere?
Anyway, I believe this feature would be very useful, and not too hard to add given the existing structure I believe.

**Comment by dnault** [comment]
You are correct, this is not currently supported. Is it something you're interested in working on?

**Comment by joffrey-bion** [comment]
I'm not sure I'll have time this week, but I'll give it a try if I have a spare evening, either this week or the next.

**Comment by joffrey-bion** [comment]
I started working on the feature, but I felt like some refactoring was calling.
Would you be opposed to a change that reorganizes the annotation processor's code?

**Comment by dnault** [comment]
Refactoring sounds good. Go for it.

**Comment by dnault** [comment]
This evening Simon Kissane submitted a [PR to add support for enum constants](https://github.com/dnault/therapi-runtime-javadoc/pull/14). Might make sense to delay refactoring until it goes in?

**Comment by dnault** [comment]
Hmmm... I see you're addressing enum constants too. Does your change makes Simon's PR redundant?

**Comment by joffrey-bion** [comment]
I believe it does make Simon's PR redundant. Although I could make use of the tests they have added regarding enums. I'm almost done in fact. Just missing decent tests for the fields now.

**Comment by joffrey-bion** [comment]
Thanks for merging!
