### ISSUE TITLE
Add links and tags elements to Comment

### ISSUE THREAD

**Issue by joffrey-bion** [dnault/therapi-runtime-javadoc#17]
It looks like the `Comment` and `CommentFormatter` classes have been designed to support the multiple elements we can find in javadoc comments.
However, all I can find is a single `CommentText` node containing the whole Javadoc comment.

It would be nice to finish this feature so that users can make use of the `CommentFormatter`.

**Comment by joffrey-bion** [comment]
Hi David, any target date for the 0.6.0 release with this feature?

**Comment by dnault** [comment]
@joffrey-bion  I can do it tomorrow if that works for you. Let me know.

**Comment by joffrey-bion** [comment]
I'm in no rush, but that would be very nice ! Thanks :)
