### ISSUE TITLE
@throws never parsed as ThrowsJavadoc

### ISSUE THREAD

**Issue by canatoly** [dnault/therapi-runtime-javadoc#21]
MethodJavadoc constructor always received empty lists of "exceptions" and "seeAlso"

please complete 
com.github.therapi.runtimejavadoc.internal.parser.JavadocParser#parseMethodJavadoc
method or give a way to substitute with custom implementation

thanx

**Comment by dnault** [comment]
Hi @canatoly , thanks for the report. I plan to take a look at this soon. My day job has been keeping me *very* busy lately, but hopefully I will have more time in a few weeks. In the mean time, let's experiment with the "help wanted" tag and see if any helpful elves appear :-)

**Comment by kirkch** [comment]
I am picking this one up - I cannot find an 'assign to me' option, so I am marking it as a comment.
