### ISSUE TITLE
Make this available in Java 7?

### ISSUE THREAD

**Issue by bbottema** [dnault/therapi-runtime-javadoc#22]
Hi @dnault,

What an innovative and interesting way of including Javadoc in runtime! Reminds me of [Lombok](https://projectlombok.org/).

I would love to use this library in my own open source library [Simple Java Mail](https://github.com/bbottema/simple-java-mail), but I'm restricted to Java 7 and your library is out of reach because of that. Is it possible to make this library available to Java 7? I know what a pain it is to not be able to use Java 8 for my own library, but since Java 7 is still is used by a [significant audience](https://www.baeldung.com/java-in-2018) I have no choice if I want to service them.

I would love to try and make this library work for my own use case, which is that I'm using Java reflection to generate CLI support and I would like to use therapi-runtime-javadoc to dynamically include the Javadoc as documentation. Otherwise I would have to maintain the documentation both in Javadoc [as well as annotations](https://stackoverflow.com/a/21889648/441662). You library would reach a lot of people if I could use it somehow.

**Comment by dnault** [comment]
Hi Benny. I'm open to this idea. Not sure what to do about the public API, which uses java.util.Optional.

**Comment by bbottema** [comment]
I'm afraid there is no elegant solution for that, it's a breaking change for sure. Best thing you can do for that is include your own version of just the Optional class. Current users would only have to update their imports.

**Comment by bbottema** [comment]
I was just looking into converting Optional for Java 7, but it is not a trivial task. I think the better option would be to use [Guava v20](https://github.com/google/guava/releases/tag/v20.0)'s battle-tested [Optional version](https://github.com/google/guava/blob/c462d69329709f72a17a64cb229d15e76e72199c/guava/src/com/google/common/base/Optional.java) or shade/shadow in something like https://github.com/MrHadiSatrio/Optional into your jar as a dependency.

Or just drop it alltogether and annotate your methods with [`@Nullable` etc.](https://stackoverflow.com/q/31157511/441662) instead, which nowadays is widely supported by IDE's and analyses tools (that's what I do as well until the world is ready to forget about Java 7).

**Comment by dnault** [comment]
Thank you, Benny!

**Comment by dnault** [comment]
Hi Benny,

Version 0.7.0 now is available on Maven Central with support for Java 7.

I ended up dodging the `@Nullable` issue by using the Null Object pattern; instead of returning null, it now returns a dummy object that models absent Javadoc.

In the project where I use this library, this change actually lead to *simpler* code than using `Optional`... so that's pretty cool. Let me know how it works for you.

Thanks,
David
