### ISSUE TITLE
ClassJavadoc#getName() should return the class name

### ISSUE THREAD

**Issue by mpe85** [dnault/therapi-runtime-javadoc#3]
I would expect `ClassJavadoc#getName()` to return the class name, just like `MethodJavadoc#getName()` returns the method name.
But currently it always returns the string "whatever".

**Comment by dnault** [comment]
Thanks for the report.

Initial investigation: culprit appears to be `JavadocParser.parseClassJavadoc`. I don't think the class name is available inside that method, so it will need to be passed in.

**Comment by dnault** [comment]
Fixed in v0.2.1 (just released).
