### ISSUE TITLE
I just thought you should know

### ISSUE THREAD

**Issue by bbottema** [dnault/therapi-runtime-javadoc#33]
I just thought you should know that I've just released [Simple Java Mail 6.0.0-rc1](https://github.com/bbottema/simple-java-mail#latest-progress), which includes [CLI support](http://www.simplejavamail.org/cli.html#navigation) based on your library. How? Because Simple Java Mail generates CLI options (using the excellent [picocli](https://picocli.info/)) using the embedded Javadoc as usage documentation!

Pretty sweet right, I have my builder api and respective documentation in one place and it's exactly the same code compared to using just the Java api.

I couldn't have done it without your excellent library (and your cooperation when I backported it to JDK7+), so a big thank you to you!

**Comment by dnault** [comment]
Hey Benny, that's awesome! Congrats on the release!
