### ISSUE TITLE
Allow the use of a package whitelist instead of annotating on each class

### ISSUE THREAD

**Issue by joffrey-bion** [dnault/therapi-runtime-javadoc#4]
Annotating every class with `@RetainJavadoc` can be really cumbersome depending on the use case, especially when there are a lot of classes involved.

In particular, it is impractical when we want to keep the Javadoc for all classes in a package because of the semantics of the package, and not of each individual class (e.g. model classes in the model package). If we often create new classes there, we need to remember to add the annotation each time.

It would be nice to be able to provide a way to use a package whitelist (maybe via a resource file) in addition to the annotation mechanism. If the class is in a white-listed package OR is annotated with `@RetainJavadoc`, then we keep the Javadoc.

The processor could, for instance, read a resource file with a specific name like `/runtime-javadoc/package-whitelist.txt`, which would contain a list of package prefixes. Then we could add features like the use of wildcards etc, but even a plain list of package prefixes would be great.

I could help if you're interested, what do you think?

**Comment by dnault** [comment]
Hi Joffrey,

Today you can apply the `@RetainJavadoc` annotation to an entire package like this:

`File: com/example/mypackage/package-info.java`

    @RetainJavadoc
    package com.example.mypackage;

    import com.github.therapi.runtimejavadoc.RetainJavadoc;

This works fine for clean builds, but is not reliable for incremental compilation. If I recall correctly, the issue was that the annotation processor only sees files that need to be compiled, and if the package-info is already compiled then the processor won't know to retain Javadoc for the files in the package.

Definitely open to pull requests if you figure out a nicer way to do this.

**Comment by joffrey-bion** [comment]
Hi @dnault, thanks for the quick reply!

I didn't know about the `package-info.java` trick, thanks for pointing that out!
If you really want to handle incremental builds, my initial resource file proposition should work.

Also, I am using your lib in the context of a doc generator that is able to read javadoc. In this context, I'm not sure I prefer forcing the user to create `package-info` files or to write a resource file with a package whitelist (I already have a package whitelist to drive the scan of the elements to document).

**Comment by dnault** [comment]
Hi @joffrey-bion,

The only reason for the `@RetainJavadoc` annotation is that I didn't realize an annotation processor can access elements that are not annotated in any way (silly me... just learned it isn't true, and that all the classes being compiled are accessible via `RoundEnvironment.getRootElements()`).

Would it be okay for your project if Javadac were retained for *every* class, or do you really want a whitelist?

**Comment by joffrey-bion** [comment]
Hi @dnault,

I believe users in general don't want to bundle the Javadoc of all classes in their class files, that would significantly and unnecessarily increase the size of their jars/wars.
The annotation approach is nice, and the whitelist option could be a good complement to it.

If you want to support including all Javadocs of all classes, maybe it would be best to somehow enable that behaviour via an option, but disable it by default. I don't know exactly how annotation processors work, and how options can be passed, but there is always the option of a resource file in the classpath.

**Comment by dnault** [comment]
Reliably locating a resource file is turning out to be difficult.

It's possible to pass options to the processor on the javac command line with the `-Akey[=value]` switch. For Gradle it might look like:

    tasks.withType(JavaCompile) {        
        options.compilerArgs << "-Ajavadoc.packages=com.example,org.example"
    }

I hear what you're saying about file size concerns. I'm leaning towards including everything by default only because it offers the best "plug and play" experience, but let me sleep on it.

**Comment by joffrey-bion** [comment]
I see your point.
I also like the plug-and-play aspect, and I'm not fond of having to tweak my Gradle compile args just get a simple result I expect.

So maybe all classes by default is the way to go after all. Would that really be "all classes", or would it only be user classes. For instance, does an annotation processor get ‘java.util.List‘ as input as well during compilation?

**Comment by dnault** [comment]
Only user classes. Annotation processor only sees the files that are being compiled from source.

**Comment by dnault** [comment]
Resolved in d651f2c04ed810fe9784d374f0b782e288deea4b
