### ISSUE TITLE
Add visitor pattern to Comment and CommentElements

### ISSUE THREAD

**Issue by kirkch** [dnault/therapi-runtime-javadoc#47]
As discussed in #31 .  The advantage of this pattern is that it removes the need for using instanceof within the CommentFormatters.

**Comment by kirkch** [comment]
This is the last of the PRs that I have for the time being.  Let me know if there is anything else that I can help with.  Once they have all gone in, please consider a release candidate.

**Comment by dnault** [comment]
Hi @kirkch , I noticed you closed the link import PR; sorry I wasn't quick enough on that one. Thank you for doing the pathfinding.

In the mean time, version 0.12.0 with your other changes is live on Maven Central. Cheers!

**Comment by kirkch** [comment]
Wonderful news re 0.12.0 going out.

It would be good to see the import resolution work complete at some point.
I am having an operation on Tuesday which will take me out of commission
for a while, and I expect that my backlog of other life business will keep
me fully booked into the new year.  In which time I am hoping that somebody
will figure out how to resolve imports during the compiler phase.   Please
keep me in the loop with the progress that gets made.

**Comment by dnault** [comment]
@kirkch Good luck with the operation; here's wishing for a speedy recovery.

**Comment by bbottema** [comment]
@dnault, @kirkch, I have an elaborate (and stateful) `ContextualCommentFormatter` subclass which doesn't compile anymore with this change, but I have no idea how I'm supposed to replace that with the new pattern.

Can we have some migration notes, or a little bit more elaborate example?

**Comment by dnault** [comment]
@bbottema The most straightforward path would be to copy the source code of `CommentFormatter` from 0.11.0 into your own project and extend that instead.
