### ISSUE TITLE
Remove external dependencies at all

### ISSUE THREAD

**Issue by magdel** [dnault/therapi-runtime-javadoc#49]
https://github.com/dnault/therapi-runtime-javadoc/blob/584558dd2fee1ccda5528d66b70b949243356515/build.gradle#L20

Hello! I just wonder if it is possible to remove dependency at all and have nice pure Java library.

**Comment by dnault** [comment]
Hi Pavel,

I'm not sure I see the benefit of implementing our own JSON library.

The `minimal-json` library is shaded/shadowed into the therapi-runtime-javadoc JAR, repackaged to avoid any possible dependency conflicts:

https://github.com/dnault/therapi-runtime-javadoc/blob/584558dd2fee1ccda5528d66b70b949243356515/build.gradle#L27-L31

From a user's perspective, the therapi-runtime-javadoc library has no external dependencies. You can verify this by inspecting [the published POM](https://repo.maven.apache.org/maven2/com/github/therapi/therapi-runtime-javadoc/0.12.0/therapi-runtime-javadoc-0.12.0.pom).

Thanks,
David

**Comment by magdel** [comment]
@dnault , thank you.
