### ISSUE TITLE
Add JavaDoc from interface to implementation

### ISSUE THREAD

**Issue by MarcelCoding** [dnault/therapi-runtime-javadoc#61]
https://github.com/springdoc/springdoc-openapi/issues/1548

Add the ability to read JavaDoc from the implementation, where the JavaDoc is actually placed at the interface.

**Comment by gebezs** [comment]
I spent some time understanding the issue and this is what I found:
* the javadoc is already extracted by the annotation processor
* it can be solved in the `therapi-runtime-javadoc` module only
* figuring out which method overrides what other or others is hard 
  * this [SO answer](https://stackoverflow.com/a/15302411) is the best solution I found so far (no library as far as I know)
  * there are a lot of edge cases
  * testing is hard
  * I didn't checked the inter module inheritance (superclass/interface in another jar)
* the strange cases are handled by the javadoc tool, so it can be checked for conform solution
  * two implemented interfaces, same method signature, different javadoc
* `{@inheritDoc}` could be solved with a little amount of extra work
* Any solution probably would solve this issue also: #62 

@dnault What do you think, did I miss anything?

**Comment by dnault** [comment]
@gebezs Thank you for the detailed analysis.

> figuring out which method overrides what other or others is hard

Maybe not _impossibly_ hard. It's hard to find out which methods *override* a method (as in that StackOverflow question), but I believe the Reflection API provides all the tools necessary to go the other way (given a method, find out which superclass / interface methods it overrides).

> @dnault What do you think, did I miss anything?

I think you covered everything! Are you interested in working on this?
