### ISSUE TITLE
Add Javadoc from overridden method if none exists

### ISSUE THREAD

**Issue by Sheikah45** [dnault/therapi-runtime-javadoc#62]
Currently if a method exists with no javadoc that overrides a method in a base class that has javadoc no java doc is returned when specifying the overriding method. 

It would be nice if the  overriden method inherited the javadoc from the base method when none exists on itself. As this is the behavior of the javadoc tools provided by oracle.

**Comment by dnault** [comment]
Thanks for reporting this. I think we can tackle it at the same time as #61, so I will close this as a duplicate.
