### ISSUE TITLE
Now working Spring project of Kotlin

### ISSUE THREAD

**Issue by hassanrehman01398** [dnault/therapi-runtime-javadoc#77]
I have a Spring project built with Kotlin. I am using a library for parsing Kotlin documentation at runtime. However, it is not functioning as expected, whereas the same method works successfully in a Java-based project. 

Kotlin version = 1.6.10
Spring version = 2.7.5

**Comment by dnault** [comment]
therapi-runtime-javadoc is not compatible with Kotlin.
