### ISSUE TITLE
Link therapi-runtime-javadoc-scribe to JCenter

### ISSUE THREAD

**Issue by joffrey-bion** [dnault/therapi-runtime-javadoc#9]
I see that the new artifact for the annotation processor is not linked to JCenter. Just pointing that out in case you didn't already request the inclusion.
Thanks a lot for the very quick response regarding the artifact separation by the way!

**Comment by dnault** [comment]
Thanks for the reminder. I requested inclusion last night, but I guess a human on the other end has to do a review and click a button.

I also applied for the `com.github.therapi` groupId on Maven Central, so hopefully the artifacts will be available there eventually.

**Comment by joffrey-bion** [comment]
Great news! Yes maven central is a hassle, I've been down this road!
But once it's done, it's pretty comfortable, especially for maven users.
Thanks again !
